[package]
name = "hello-service"
version = "0.1.0"
authors = ["Tim Park <timfpark@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
actix-web-prom = "0.5"
env_logger = "0.8.3"
